### ISSUE TITLE
Broken link in Open Autonomy docs

### ISSUE THREAD

**Issue by dagacha** [valory-xyz/docs#78]
The link

https://docs.autonolas.network/open-autonomy/guides/set_up.md#set-up-the-framework

in page 

https://docs.autonolas.network/demos/hello-world/#architecture-of-the-demo is broken.

It should instead be https://docs.autonolas.network/open-autonomy/guides/set_up/

**Comment by jmoreira-valory** [comment]
Addressed on https://github.com/valory-xyz/hello-world/pull/19
